### ISSUE TITLE
Building fails due to fno-common being the default in recent versions of gcc

### ISSUE THREAD

**Issue by copy** [ocaml-cross/opam-cross-windows#191]
Running `opam install ocaml-windows64` results in this error:

```
/usr/lib/gcc/x86_64-w64-mingw32/10.1.0/../../../../x86_64-w64-mingw32/bin/ld: libcamlrun.a(backtrace_b.o):~/.opam/windows/.opam-switch/build/ocaml-windows64.4.08.0/runtime/backtrace.c:31: multiple definition of `caml_debug_info'; libcamlrun.a(backtrace_byt_b.o):/home/fabian/.opam/windows/.opam-switch/build/ocaml-windows64.4.08.0/runtime/backtrace_byt.c:47: first defined here
```

Which has [already been fixed](https://github.com/ocaml/opam-repository/pull/16583) in OCaml >= 4.09.1.

**Comment by toots** [comment]
Thanks for the report. Hopefully we'll find time to update the ocaml version in this repo soon..

**Comment by toots** [comment]
Could you check if the issue still occurs with `ocaml-windows.4.11.2`?

**Comment by copy** [comment]
It's fixed with ocaml-windows.4.11.2. Cheers!
