### ISSUE TITLE
ppx_tools_versioned-windows is broken with 4.12.0

### ISSUE THREAD

**Issue by toots** [ocaml-cross/opam-cross-windows#211]
See: https://github.com/ocaml-cross/opam-cross-windows/actions/runs/1496855762

@WardBrian, do you think you could have a minute to check it out?

**Comment by WardBrian** [comment]
I certainly can, but likely not until after the holiday. My guess is I missed a dependency which is getting installed by something else when it’s used as part of core_kernel?

**Comment by toots** [comment]
Thanks! Of course!

I'm not sure. All the dependencies seem to the up-to date, there's only one, `ocaml-migrate-parsetree-windows` and it's already at the latest on `opam` I believe, `2.2.0`.

This error seems to be a build error related to the `ocaml-migrate-parsetree` stuff.

**Comment by WardBrian** [comment]
Ah, it seems like it can’t use OCaml-migrate-parsetree 2.0 or later:

https://github.com/ocaml/opam-repository/blob/master/packages/ppx_tools_versioned/ppx_tools_versioned.5.4.0/opam

not sure if that renders it completely incompatible with 4.12 or not, but we should update the opam file to enforce that. 

I think there are probably more instances where packages need upper bounds that didn’t originally exist/matter because the repo didn’t have anything new enough to cause problems

**Comment by toots** [comment]
That works, thanks so much, I didn't realize the deps could have changed since `4.12.0` had been uploaded!

**Comment by WardBrian** [comment]
I’m not sure how the master opam repo handles things like this - when that package was first added, it didn’t have the < 2.0.0 constraint, because 2.0.0 didn’t exist yet, so they must have added it later somehow (hopefully automated? But who knows)

**Comment by WardBrian** [comment]
Seems like it happened in https://github.com/ocaml/opam-repository/pull/16999, but of course that wouldn’t affect this repo. Tricky without some way of monitoring the upstream package

**Comment by toots** [comment]
For the dune-based packages, it should be possible to write scripts to automatize the translation of opam files for the windows build. We might need to overshoot the deps, i.e. add `foo-windows` and `foo` for each dependency on `foo` but, then, we could routinely re-import all dune-based packages from the upstream repository. There's already a programatic access to `.opam` files here: https://github.com/ocaml/opam-file-format
