### ISSUE TITLE
OCaml-windows 4.12.0 no longer builds

### ISSUE THREAD

**Issue by WardBrian** [ocaml-cross/opam-cross-windows#258]
I have a [rarely-run github action](https://github.com/WardBrian/stanc3/blob/master/.github/workflows/binaries.yml) which stopped building recently.

The error is

```
   # x86_64-w64-mingw32-gcc -c -O2 -mms-bitfields -fno-strict-aliasing -Wall -fno-tree-vrp -g  -DCAML_NAME_SPACE -DUNICODE -D_UNICODE -DWINDOWS_UNICODE=1 -DOCAML_STDLIB_DIR='L"/home/runner/work/stanc3/stanc3/_opam/windows-sysroot/lib/ocaml"' -I/home/runner/work/stanc3/stanc3/_opam/lib/flexdll-windows -DCAMLDLLIMPORT=  \
  #   -o prims.o prims.c
  # /home/runner/work/stanc3/stanc3/_opam/lib/flexdll-windows/flexlink -chain mingw64 -stack 16777216 -link -static-libgcc -exe -link "-municode" -o ocamlrun.exe prims.o libcamlrun.a -lws2_32 -lversion 
  # /bin/sh: 1: /home/runner/work/stanc3/stanc3/_opam/lib/flexdll-windows/flexlink: not found
  # make[1]: *** [Makefile:265: ocamlrun.exe] Error 127
  # make[1]: Leaving directory '/home/runner/work/stanc3/stanc3/_opam/.opam-switch/build/ocaml-windows64.4.12.0/runtime'
  # make: *** [Makefile:141: coldstart] Error 2
```

**Comment by toots** [comment]
I need to revert some recent changes with `flexlink`, will do soon. I would, however, consider building `4.14.0`. There were a lot of recent cleanup there that should really make it the preferred compiler now. See: https://github.com/ocaml-cross/opam-cross-windows/pull/257

**Comment by WardBrian** [comment]
I believe 4.14 requires changing our usages of the Jane Street libraries to account for their new structure, so while it will be done eventually it would be nice to build with 4.12 a little longer
