### ISSUE TITLE
Ocaml 5 support

### ISSUE THREAD

**Issue by ada2k** [ocaml-cross/opam-cross-windows#275]
Hello, apologies if an issue is not the right venue for this, but are there plans to update this project for OCaml 5? Is this limited by the incompatibility with MSVC in 5.0.0? The upcoming native opam release should boost windows adoption and I feel this is a compelling argument for having a good, up to date cross compiler :)

**Comment by toots** [comment]
Hi @ada2k. I have not looked into at at all yet. I would love to but this is time dependent for me. I used this repository primarily for liquidsoap builds. Out next major development cycle involves leveraging OCaml's domain so I will definitely look at it when this happens. Until then, I am more than happy to guide anyone. @WardBrian has also worked on upgrading ocaml in the past and may be able to help.

**Comment by WardBrian** [comment]
I think the changes from 4 -> 5 are probably above my limited porting experience :)

I think that the improved (native) Windows support in OPAM may make my use case for cross-compiling smaller, rather than more important, but it is too early to tell still

**Comment by ada2k** [comment]
That is fair, however in my experience the windows ports of ocaml can be painfully slow and unreliable due to their use of cygwin, which isn’t going away in opam 2.2 AFAIK. In a project I was recently working on, the current cross compiler was an order of magnitude faster than any windows build I could find. Honestly, the main thing holding this back after using it more in practice is not being stuck on ocaml 4; the type of applications that need to run on windows are not typically large, well-oiled servers. The much bigger problem is the general package support, which is most likely a much bigger issue to tackle.

Sent from Outlook for iOS<https://aka.ms/o0ukef>
________________________________
