### ISSUE TITLE
Cannot install `ocaml-windows` 5.1.1

### ISSUE THREAD

**Issue by Chimrod** [ocaml-cross/opam-cross-windows#313]
I have errors when I run the command `opam install ocaml-windows` in my switch `ocaml-variants.5.1.1+options`.

I’m using debian, and the mingw compiler provided by the distribution. In attachement, you will see the files generated by opam in the installation.

[ocaml-windows64-562769-031fff.env.log](https://github.com/ocaml-cross/opam-cross-windows/files/14424340/ocaml-windows64-562769-031fff.env.log)

[ocaml-windows64-562769-031fff.info.log](https://github.com/ocaml-cross/opam-cross-windows/files/14424341/ocaml-windows64-562769-031fff.info.log)

[ocaml-windows64-562769-031fff.out.log](https://github.com/ocaml-cross/opam-cross-windows/files/14424342/ocaml-windows64-562769-031fff.out.log)

**Comment by toots** [comment]
Ok I think that this is b/c of the removal of `-lgcc_eh`. I'll revisit this change to be more finer-grained.

**Comment by Chimrod** [comment]
The latest commit does not solve the issue:

Output from the terminal:

```
These patches didn't apply at /home/sebastien/.opam/5.1.1+options/.opam-switch/build/ocaml-windows64.5.1.1:
  - patches/configure.patch: "/usr/bin/patch -p1 -i
    /home/sebastien/.opam/log/processed-patch-896957-49771f" exited with
    code 1
```

And the content of the out:

```
patching file configure
Hunk #1 FAILED at 14274.
1 out of 1 hunk FAILED -- saving rejects to file configure.rej
can't find file to patch at input line 25
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|opam@7bc71e662445:/tmp/ocaml$ diff -urN configure configure.new
|--- configure	2024-02-27 21:22:55.384420013 +0000
|+++ configure.new	2024-02-27 21:19:10.686935006 +0000
--------------------------
File to patch: 
Skip this patch? [y] 
Skipping patch.
1 out of 1 hunk ignored
```

**Comment by toots** [comment]
Yeah I pushed the wrong patch. Try the latest `main` now.

**Comment by toots** [comment]
Ha wait sorry one sec.

**Comment by toots** [comment]
Should be good now.

**Comment by Chimrod** [comment]
I confirm, I’ve been able to install without any issues.

Thanks a LOT for your work on the repository, it’s awesome!
