### ISSUE TITLE
error compiling dune-windows (OCaml 5.1.1)

### ISSUE THREAD

**Issue by maroneze** [ocaml-cross/opam-cross-windows#315]
Hello,

I just heard about this project in the announcement of Ocaml-windows 5.1.1, and I'd like to try it on a dune-based project.

Using OCaml 5.1.1, I managed to add the repository, install `ocaml-windows`, and some packages such as `ppxlib-windows`, but `dune-windows 3.2.0` is failing (`** Cannot resolve symbols for /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libws2_32.a(lib64_libws2_32_a-WspiapiLegacyGetNameInfo.o/...`).

Before going further, I'd like to check if this is somehow expected, and how should I proceed in debugging this. The announcement message, "Fortunately, adding new dune-based packages has become remarkably easy thanks to dune’s great cross-compilation support" led me to think that dune was working "out of the box", but given there are only 3 versions of it in `dune-windows`, it seems I misunderstood it. Perhaps I do not need `dune-windows` at all?

**Comment by toots** [comment]
Thanks for the report! `dune-windows` is only required if you need any of the dune libraries. For building and such, you only need the native host `dune`.

That being said, something is wrong with the cross-compilation configuration. Could you describe what system you are building on and how you installed `mingw-w64`? Thanks!

**Comment by maroneze** [comment]
Oh, I hadn't even realized that it would use a cross-compiler already installed in my system, I thought it would install everything by itself!

I'm using Fedora 38, I installed mingw64 a while ago using Fedora's dnf (I have several mingw64-* dnf packages installed). For completeness, here's the final part of opam's log, indicating the issue are the `chk` functions:

```
** Cannot resolve symbols for /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libws2_32.a(lib64_libws2_32_a-WspiapiLegacyGetNameInfo.o/
lib64_libws2_32_a-WspiapiLoad.o/
lib64_libws2_32_a-WspiapiGetAddrInfo.o/
lib64_libws2_32_a-WspiapiGetNameInfo.o/
lib64_libws2_32_a-WspiapiFreeAddrInfo.o/

):
 __chk_fail
** Cannot resolve symbols for /usr/x86_64-w64-mingw32/sys-root/mingw/lib/libws2_32.a(lib64_libws2_32_a-WspiapiLoad.o/
lib64_libws2_32_a-WspiapiGetAddrInfo.o/
lib64_libws2_32_a-WspiapiGetNameInfo.o/
lib64_libws2_32_a-WspiapiFreeAddrInfo.o/

):
 __strcat_chk
 __strcpy_chk
```

There are newer mingw64 packages in Fedora 39 and 40 (mine is `mingw64-crt-10.0.0-4.fc38.noarch`; there are `mingw64-crt-11.0.0-2.fc39.noarch` and `mingw64-crt-11.0.1-3.fc40.noarch`), so probably upgrading it could fix the issue.

I don't know when I'll have time to upgrade it, though, so in the meanwhile it might be better to close this issue, and I'll reopen if it still happens with a newer mingw64 (and if I do need `dune-windows`).

**Comment by toots** [comment]
Ok!
