### ISSUE TITLE
Could we configure the cross compiler so that os_type = Win32 ?

### ISSUE THREAD

**Issue by pirbo** [ocaml-cross/opam-cross-windows#60]
`ocamlfind -toolchain windows ocamlc -config`
returns
```
[...]
os_type: Unix
[...]
```
which forbids me to update (easily) lwt to version 3.2.0 (and causes #27 if I'm not mistaken).

Actually, in order to configure the "unix" backend of lwt, jbuilder relies on the output of `ocaml -config`...

**Comment by toots** [comment]
+1 on this one. I can provide a patch if we agree on it.

**Comment by whitequark** [comment]
@toots Can you please investigate the root cause? It's related to the Sys.os_type primitive; we might need to patch the codegen to fix that.

**Comment by pirbo** [comment]
Indeed:
`wine ~/.opam/4.04.0/windows-sysroot/bin/ocamlopt.exe -config` answers correctly
`[...] os_type: Win32 [...]`
but
`~/.opam/4.04.0/.opam/for_nightly/bin/ocamlrun ~/.opam/4.04.0/windows-sysroot/bin/ocamlopt.exe -config` i.e. `~/.opam/4.04.0/windows-sysroot/bin/ocamlopt -config` answers
`os_type: Unix`

This is because `Sys.os_type` comes from `Sys.get_config` which is an `external` and that's made on purpose to make (normal) byte code executable cross-platform!

The ugliest possible hack would be to do (for the all cross compiler) in `stdlib/sys.mlp`
- let (os_type, _, _) = get_config()
+ let (os_type, _, _) = "Win32"
but that's looks super dirty.

**Comment by toots** [comment]
I remember having to do that with the Debian cross-compiler patches back in the days. Rather than patching, it looks like the perfect candidate for integration upstream. Now, how should cross-compilation be properly marked and detected by the compiler?
