### ISSUE TITLE
opam-cross-windows for OCaml 4.02.3?

### ISSUE THREAD

**Issue by tajmone** [ocaml-cross/opam-cross-windows#65]
Is cross-windows also available for OCaml 4.02.3?

Can I just switch to it using `opam switch 4.02.3+32bit`? or is this project tied to the 4.04.0 version?

I'm asking because I'm trying to compile an old OCaml project which is known to fail with OCaml 4.04.0, but compiles fine with 4.02.3.

Is this the first release of this project? will it be maintained throughout future versions of OCaml?

**Comment by hcarty** [comment]
It's something of a snapshot branch without ongoing support/updates, but there is the `ocaml-4.02.3` branch you can use if you are tied to that version of the compiler.

**Comment by whitequark** [comment]
Indeed, you'll need to use the branch.

Updates for opam-cross-windows are provided by volunteers; ideally the need for this project would disappear as opam and build systems will natively gain the ability to cross-compile. (Jbuilder is getting there quickly.)
