### ISSUE TITLE
Name of default toolchain?

### ISSUE THREAD

**Issue by wintersteiger** [ocaml-cross/opam-cross-windows#66]
Stupid question, but sometimes while building packages, I need to use tools from one toolchain to override tools from other toolchains. `ocamlfind -toolchain windows ocamldep` works just fine, but during the build of a package I need `ocamlfind -toolchain DEFAULT ocamldep` to override explicit `-toolchain` commands and/or the `OCAMLFIND_TOOLCHAIN` environment variable.

Stuff like `sh -c unset OCAMLFIND_TOOLCHAIN; which ocamldep` kind of works sometimes, but there has to be a better way.

**Comment by whitequark** [comment]
Try `-toolchain ''`
