### ISSUE TITLE
ocaml-migrate-parsetree-windows >= v1.0.10

### ISSUE THREAD

**Issue by gpetiot** [ocaml-cross/opam-cross-windows#79]
It would be great to have a windows package for ocaml-migrate-parsetree >= v1.0.10. Is anybody working on this ? If not I will try to take a look.
(We need it for `ocamlformat`)

**Comment by toots** [comment]
Just pushed a PR that has it, needs a couple of fixes but should be good.

**Comment by gpetiot** [comment]
Thank you, I missed your PR.
I see you upgraded ocaml-migrate-parsetree to v1.0.9, unfortunately the support for OCaml 4.07 ASTs has been added in v1.0.10.

**Comment by toots** [comment]
It's in the PR now! Just needs a couple more fixes, tho.

**Comment by toots** [comment]
Done!

**Comment by gpetiot** [comment]
Thank you!

**Comment by VMatthijs** [comment]
If I try `opam install ocaml-migrate-parsetree-windows`, it fails with the message

```
#=== ERROR while compiling ocaml-migrate-parsetree-windows.1.0.11 =============#
# context     2.0.0 | linux/x86_64 | ocaml-base-compiler.4.07.0 | git://github.com/ocaml-cross/opam-cross-windows
# path        ~/.opam/4.07.0/.opam-switch/build/ocaml-migrate-parsetree-windows.1.0.11
# command     ~/.opam/4.07.0/bin/jbuilder build -p ocaml-migrate-parsetree -j 7 -x windows
# exit-code   1
# env-file    ~/.opam/log/ocaml-migrate-parsetree-windows-9263-05296d.env
# output-file ~/.opam/log/ocaml-migrate-parsetree-windows-9263-05296d.out
### output ###
# Hash collision between set of ppx drivers:
# - ppx1, ppx2
# - ppx1, ppx2
```

I'm running opam 2.0.0. Tried with dune 1.0, 1.4, 1.5.1 and 1.6. Could this be a bug in ocaml-migrate-parsetree-windows?
